<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <title>Flight Route Simulator</title>
        <script
            src='https://code.jquery.com/jquery-3.1.1.min.js'
            integrity='sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8='
            crossorigin='anonymous'>
        </script>
        <script type="text/javascript" src="phaser_src/js/phaser.min.js"></script>
        <script type="text/javascript" src="phaser_src/js/path.js"></script>
        <script type="text/javascript" src="phaser_src/js/airplane.js"></script>
        <script type="text/javascript" src="phaser_src/js/boot.js"></script>
        <script type="text/javascript" src="phaser_src/js/preload.js"></script>
        <script type="text/javascript" src="phaser_src/js/game.js"></script>

        <style>
          body {
            padding: 0px;
            margin: 0px;
          }
          </style>
    </head>

    <body>  
        <script src="phaser_src/js/main.js"></script>
    </body>
</html>
